Configure-0.1.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,7 @@
 #!/bin/bash
 # Automatic make file configuration script
+# Released under the MIT License
+# Copyright (c) 2017 Michael Lazear
 
 # Project information
 SOURCE_DIR=src
@@ -7,11 +9,13 @@ INCLUDE_DIR=include
 BUILD_DIR=build
 OUTPUT=Makefile
 PROJECT=$(basename "$PWD")
+PREFIX=/usr/local/bin
 
 # Build machine and compiler information
 CC=$(which cc)
 CMACHINE=$(cc -dumpmachine)
 CVERSION=$(cc -dumpversion)
+CFLAGS="-O2 -Wall -Werror -Wextra"
 ARCH=$(uname -m)
 OS=$(uname -s)
 STDC_VERSION=""
@@ -21,19 +25,67 @@ CONFIG_DIR=.config
 CTEST=test.c
 LOG=log
 
+check_header() {
+	printf "Checking for $1... "
+	cat << ENDHEADER > $CONFIG_DIR/header.c 
+#include "$1"
+int main(void) {
+	return 0;
+}
+ENDHEADER
+$CC -Wall -Wextra -Werror $CONFIG_DIR/header.c 2> /dev/null
+if [ $? -eq 0 ]; then
+		echo "success"
+		name=$(echo $1 | sed 's/\.h//g')
+		echo "#define CONFIGURE_${name^^}" 1 >> $INCLUDE_DIR/configure.h
+		rm ./a.out
+	else
+		echo "fail"
+		echo "#define CONFIGURE_${name^^}" 0 >> $INCLUDE_DIR/configure.h
+fi
+
+}
+
+check_function() {
+	printf "Checking for function $2 in $1... "
+	cat << ENDHEADER > $CONFIG_DIR/function.c 
+#include "$1"
+int main(void) {
+	$2(${@:3});
+	return 0;
+}
+ENDHEADER
+$CC -Wall -Wextra -Werror $CONFIG_DIR/function.c 2> /dev/null
+
+if [ $? -eq 0 ]; then
+		echo "success"
+		echo "#define CONFIGURE_${2^^} 1" >> $INCLUDE_DIR/configure.h
+		rm ./a.out	
+	else
+		echo "fail"
+		echo "#define CONFIGURE_${2^^} 0" >> $INCLUDE_DIR/configure.h
+fi
+
+}
+
 # Determine what version of standard C library we support
-stdc_ver() {
+check_stdc() {
+printf "Checking which version of the C standard compiler supports... "
 cat << END_STDC > $CONFIG_DIR/$CTEST
-#include <stdio.h>
+#include "stdio.h"
 int main(int argc, char** argv) {
 	printf("%ld", __STDC_VERSION__);
 	return 0;
 }
 END_STDC
-
-	$CC $CONFIG_DIR/$CTEST
-	STDC_VERSION=$(./a.out)
-	rm ./a.out
+$CC $CONFIG_DIR/$CTEST 2> /dev/null
+if [ $? -eq 0 ]; then
+		STDC_VERSION=$(./a.out)
+		echo $STDC_VERSION
+		rm ./a.out
+	else
+		echo "__STDC_VERSION__ not defined"
+fi
 }
 
 # Create a makefile
@@ -51,9 +103,10 @@ export ARCH     = $ARCH
 export CC       = $CC
 export CCVER    = $CVERSION
 export STDC_VER = $STDC_VERSION
-export CFLAGS   = -O2 -Wall -Wextra
+export CFLAGS   = $CFLAGS
 
 # Project information
+export PREFIX   = $PREFIX
 export PROJECT  = $PROJECT
 export VERSION  = 0.1.0
 
@@ -77,7 +130,13 @@ clean:
 
 dist: clean
 	@echo "creating distribution archive $(PROJECT)-$(VERSION).tar.gz"
-	@tar -cvf $(PROJECT)-$(VERSION).tar.gz configure $(BUILD) $(SRC_DIR) $(INC_DIR)
+	@tar -cvf $(PROJECT)-$(VERSION).tar.gz configure $(TARGET) $(SOURCE) $(HEADERS)
+
+install: $(TARGET)
+	@echo "installing $(PROJECT) in $(PREFIX)"
+	@cp $(TARGET) $(PREFIX)/$(PROJECT)-$(VERSION)
+	@ln $(PREFIX)/$(PROJECT)-$(VERSION) $(PREFIX)/$(PROJECT) 
+
 
 %.o: %.c
 	@echo "cc $<"
@@ -90,6 +149,7 @@ EOF
 }
 
 create_accessories() {
+if [ ! -f README.md ]; then
 cat << ENDREADME > README.md 
 # $PROJECT-0.1.0
 
@@ -103,7 +163,8 @@ make install
 ### License
 See LICENSE file
 ENDREADME
-
+fi
+if [ ! -f LICENSE ]; then
 cat << ENDLICENSE > LICENSE
 MIT License
 
@@ -127,33 +188,84 @@ LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 ENDLICENSE
-
+fi
+if [ ! -f .gitignore ]; then	
 cat << ENDIGNORE > .gitignore
 *.o
 *.a
 .config
 ENDIGNORE
+fi
 }
 
 clean() {
 	rm -rf $CONFIG_DIR
 	rm -rf $OUTPUT
 	rm -rf $BUILD_DIR
-	rm -rf README.md
-	rm -rf LICENSE
 }
 
-if [[ $1 == --clean ]]; then
-	clean
-	exit
-fi
+TEMP=`getopt -o hp --long help,clean,prefix:,cc:,cflags: -n 'configure' -- "$@"`
 
-clean
+# Note the quotes around `$TEMP': they are essential!
+eval set -- "$TEMP"
+
+while true ; do
+	case "$1" in
+		-h|--help)
+			echo "$0"
+			echo "--clean:    clean up configuration files and build directory"
+			echo "--prefix=:  set install location"
+			echo "--cc=:      set C compiler"
+			echo "--cflags=:  set C compiler flags"
+			echo "--help:     display this text"
+			exit 0;;
+		--clean) 
+			clean
+			exit 0;;
+		-p|--prefix) 
+			PREFIX="$2";
+			shift 2 ;;
+		--cc) 
+			CC="$2";
+			shift 2;;
+		--cflags)
+			CFLAGS="$2";
+			shift 2;;
+		--)  
+			shift;
+			break ;;
+		*) 
+			echo "$0 error: unknown argument!" ; 
+			exit 1 ;;
+	esac
+done
+
+
 mkdir -p $CONFIG_DIR
 mkdir -p $SOURCE_DIR
 mkdir -p $INCLUDE_DIR
 mkdir -p $BUILD_DIR
 
-stdc_ver
+if [ ! $(which $CC) ]; then
+	echo "$0 error: C compiler not found"
+	exit 1;
+fi
+
+check_stdc
 create_makefile
 create_accessories
+
+# Begin dependency/header check 
+echo "/* This file was automatically generated by $1 */" > $INCLUDE_DIR/configure.h
+echo "#ifndef _CONFIGURE_H_" >> $INCLUDE_DIR/configure.h
+echo "#define _CONFIGURE_H_" >> $INCLUDE_DIR/configure.h
+
+check_header "stdio.h"
+check_header "stddef.h"
+check_header "stdint.h"
+check_header "stdlib.h"
+check_header "stdatomic.h"
+check_function "stdio.h" printf '"%d"', 1
+
+
+echo "#endif" >> $INCLUDE_DIR/configure.h
