Add additional Make targets, fix version numbering scheme

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,6 +9,7 @@ INCLUDE_DIR=include
 BUILD_DIR=build
 OUTPUT=Makefile
 PROJECT=$(basename "$PWD")
+PROJECT_VER=""
 PREFIX=/usr/local/bin
 
 # Build machine and compiler information
@@ -107,7 +108,7 @@ export CFLAGS   = $CFLAGS
 # Project information
 export PREFIX   = $PREFIX
 export PROJECT  = $PROJECT
-export VERSION  = 0.1.0
+export VERSION  = $PROJECT_VER
 
 EOF
 cat << 'EOF' >> $OUTPUT
@@ -120,7 +121,7 @@ export SOURCE   = $(wildcard $(SRC_DIR)/*.c)
 export OBJECTS  = $(SOURCE:.c=.o)
 export TARGET   = $(BUILD)/$(PROJECT)
 
-.PHONY: all clean dist
+.PHONY: all clean dist install uninstall upgrade
 
 all: $(TARGET)
 
@@ -134,8 +135,18 @@ dist: clean
 install: $(TARGET)
 	@echo "installing $(PROJECT) in $(PREFIX)"
 	@cp $(TARGET) $(PREFIX)/$(PROJECT)-$(VERSION)
-	@ln $(PREFIX)/$(PROJECT)-$(VERSION) $(PREFIX)/$(PROJECT) 
+	@ln -s $(PREFIX)/$(PROJECT)-$(VERSION) $(PREFIX)/$(PROJECT) 
 
+uninstall:
+	@echo "uninstalling $(PROJECT) in $(PREFIX)"
+	if [ -f $(PREFIX)/$(PROJECT) ]; then \
+		rm -rf $(PREFIX)/$(PROJECT); \
+		rm -rf $(PREFIX)/$(PROJECT)-$(VERSION); \
+	fi
+upgrade:
+	@rm -rf $(PREFIX)/$(PROJECT)
+	@cp $(TARGET) $(PREFIX)/$(PROJECT)-$(VERSION)
+	@ln -s $(PREFIX)/$(PROJECT)-$(VERSION) $(PREFIX)/$(PROJECT) 
 
 %.o: %.c
 	@echo "cc $<"
@@ -151,7 +162,7 @@ create_accessories() {
 
 if [ ! -f README.md ]; then
 cat << ENDREADME > README.md 
-# $PROJECT-0.1.0
+# $PROJECT-$PROJECT_VER
 
 ### Building
 \`\`\`
@@ -204,6 +215,17 @@ clean() {
 	rm -rf $BUILD_DIR
 }
 
+
+### Script begins here ###
+
+# If Makefile exists, grab the existing PROJECT_VER and CFLAGS variables and use them
+if [ -f $OUTPUT ]; then
+	PROJECT_VER=$(cat $OUTPUT | grep "export VERSION" | sed -e 's/^.*=[ ]*//g')
+	CFLAGS=$(cat $OUTPUT | grep "export CFLAGS" | sed -e 's/^.*=[ ]*//g')
+else
+	PROJECT_VER="0.1.0"
+fi
+
 TEMP=`getopt -o hp --long help,clean,prefix:,cc:,cflags: -n 'configure' -- "$@"`
 
 # Note the quotes around `$TEMP': they are essential!
@@ -213,11 +235,11 @@ while true ; do
 	case "$1" in
 		-h|--help)
 			echo "$0"
-			echo "--clean:    clean up configuration files and build directory"
-			echo "--prefix=:  set install location"
-			echo "--cc=:      set C compiler"
-			echo "--cflags=:  set C compiler flags"
-			echo "--help:     display this text"
+			echo "--help:                 display help menu
+--prefix=/path/to/dir   set the installation directory  default /usr/local/bin
+--cc=/path/to/compiler  set the C compiler              default /usr/bin/cc
+--cflags=\"-Wall -O3\"    set the C compiler flags        default -O2 -Wall -Werror -Wextra
+--clean                 clean up the config and build directories, regenerate Makefile"
 			exit 0;;
 		--clean) 
 			clean
@@ -240,19 +262,28 @@ while true ; do
 	esac
 done
 
+if [ ! $(which $CC) ]; then
+	echo "$0 error: C compiler not found"
+	exit 1;
+fi
+
+echo "Configuring for $PROJECT-$PROJECT_VER"
 
 mkdir -p $CONFIG_DIR
 mkdir -p $SOURCE_DIR
 mkdir -p $INCLUDE_DIR
 mkdir -p $BUILD_DIR
 
-if [ ! $(which $CC) ]; then
-	echo "$0 error: C compiler not found"
-	exit 1;
+if [ -f $PREFIX/$PROJECT ]; then
+	echo "Warning: $PREFIX/$PROJECT already exists - suggest changing project name before install"
+fi
+
+if [ ! -f configure ]; then
+	echo "Copying configure script to $(pwd)"
+	cp $0 configure
 fi
 
 # Begin dependency/header check 
-
 
 cat << ECONFIG > $CONFIG_HEADER
 /* This file was automatically generated by $0 */
@@ -260,7 +291,7 @@ cat << ECONFIG > $CONFIG_HEADER
 #define _CONFIGURE_H_
 
 #define CONFIGURE_NAME      "$PROJECT"
-#define CONFIGURE_VERSION   "0.1.0"
+#define CONFIGURE_VERSION   "$PROJECT_VER"
 #define CONFIGURE_ARCH      "$ARCH"
 ECONFIG
 
